# Generated by Django 2.1.4 on 2018-12-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleid', models.AutoField(max_length=12, primary_key=True, serialize=False, verbose_name='文章id')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='文章添加时间')),
                ('userid', models.IntegerField(max_length=18, verbose_name='文章用户id')),
                ('abstract', models.CharField(default='尚无简介', max_length=40, verbose_name='文章简介')),
                ('categoryname', models.CharField(max_length=20, verbose_name='文章标签')),
                ('a_content', models.CharField(default='尚无内容', max_length=20000, verbose_name='文章内容')),
                ('a_state', models.IntegerField(choices=[(1, '正常'), (0, '删除')], default='1', verbose_name='文章状态')),
                ('readnum', models.IntegerField(default='0', max_length=10, verbose_name='文章阅读量')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(max_length=2, primary_key=True, serialize=False, verbose_name='标签id')),
                ('categoryname', models.CharField(max_length=18, unique=True, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.AutoField(max_length=12, primary_key=True, serialize=False, verbose_name='评论id')),
                ('userid', models.IntegerField(max_length=18, verbose_name='评论用户id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='评论添加时间')),
                ('articleid', models.IntegerField(max_length=12, verbose_name='评论文章id')),
                ('c_content', models.CharField(default='尚无内容', max_length=200, verbose_name='评论内容')),
                ('c_state', models.IntegerField(choices=[(1, '正常'), (0, '删除')], default='1', verbose_name='评论状态')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(max_length=9, primary_key=True, serialize=False, verbose_name='用户id')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('username', models.CharField(max_length=18, unique=True, verbose_name='用户名')),
                ('role', models.IntegerField(choices=[(0, '禁言用户'), (1, '普通用户'), (2, '管理员用户')], default='0', verbose_name='用户权限')),
            ],
        ),
    ]
