# Generated by Django 2.1.4 on 2018-12-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='readnum',
            field=models.IntegerField(default='0', verbose_name='文章阅读量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='userid',
            field=models.IntegerField(verbose_name='文章用户id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='articleid',
            field=models.IntegerField(verbose_name='评论文章id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(verbose_name='评论用户id'),
        ),
    ]
