# Generated by Django 2.1.4 on 2018-12-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181227_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='state',
            field=models.IntegerField(choices=[(1, '正常'), (0, '删除')], default='1', verbose_name='标签状态'),
        ),
    ]
